apiVersion: v1
kind: Service
metadata:
  labels:
    app: stub-helm-chart
  name: externalgrafana
  namespace: {{ .Release.Namespace }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: website
  type: LoadBalancer
