apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: externalgrafana
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
