apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: svcacct1

